#!/usr/bin/env bash
# Idempotent repository bootstrap for the Agri Ledger Cloud Agent environment.
# Installs a local MySQL server (the app rejects Postgres), seeds a dev database
# and admin/observe users, writes a local-only .env, and installs npm deps.
set -euo pipefail

cd "$(dirname "$0")/.."

DB_NAME="agri"
DB_USER="agri"
DB_PASS="agri_pw_123"

echo "==> Ensuring MySQL server is installed"
if ! command -v mysqld >/dev/null 2>&1; then
  sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq mysql-server-8.0
fi

echo "==> Starting MySQL"
sudo service mysql start || true

# Wait for the server socket to accept connections.
for _ in $(seq 1 30); do
  if sudo mysqladmin ping >/dev/null 2>&1; then break; fi
  sleep 1
done

echo "==> Creating database and application user (idempotent)"
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED WITH caching_sha2_password BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL

echo "==> Writing local .env (dev-only credentials; not for production)"
if [ ! -f .env ]; then
  cat > .env <<ENV
# Local Cloud Agent dev config (generated by .cursor/install.sh)
DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@127.0.0.1:3306/${DB_NAME}
JWT_SECRET=local-dev-jwt-secret-please-change-0123456789abcdef
ENV
fi

echo "==> Installing npm dependencies"
npm install

echo "==> Seeding admin/observe users and schema"
node scripts/create-admin.mjs --username admin --password admin123
node scripts/create-admin.mjs --username observe --password observe123 --role observe

echo "==> Install complete"
